# SPDX-FileCopyrightText: Copyright (c) 2018-2025 slowtec GmbH <post@slowtec.de>
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Continuous integration

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            runner_os: ubuntu-latest
          - target: x86_64-apple-darwin
            runner_os: macos-latest
          - target: x86_64-pc-windows-msvc
            runner_os: windows-latest

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install all-features cargo subcommand
        run: cargo install cargo-all-features

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          # Two jobs might share the same default target but have different build targets.
          shared-key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.target }}

      - name: Build tests with all features enabled
        run: >-
          cargo test --workspace --locked --target ${{ matrix.target }} --all-features --all-targets
          --no-run

      - name: Run tests with all features enabled
        if: matrix.run_tests
        run: >-
          cargo test --workspace --locked --target ${{ matrix.target }} --all-features --all-targets
          -- --nocapture --quiet

      - name: Test workspace with all feature combinations
        run: cargo all-features test --workspace

      - name: Build workspace documentation with all features enabled
        run: cargo doc --workspace --locked --target ${{ matrix.target }} --all-features

      - name: Build release with default features
        run: cargo build --locked --target ${{ matrix.target }} --all-targets --profile release
